projects:
  badges:
    coverage:
      dependencies: []
      artifacts:
        - builder: '@liquid-labs/sdlc-projects-badges-coverage'
          version: 1.0.0-alpha.2
          priority: 0
          content: >-
            [![coverage:
            99%](./.readme-assets/coverage.svg)](https://github.com/liquid-labs/find-plus/pulls?q=is%3Apr+is%3Aclosed)
          path: /Users/zane/playground/find-plus/.readme-assets/coverage.svg
          purpose: Test coverage badge for README.md.
