# This file was generated by @liquid-labs/catalyst-builder-workflow-local-make-
# node. Refer to https://npmjs.com/package/@liquid-labs/catalyst-builder-workflow-
# local-make-node for further details

# Locally modified (not regenerated verbatim): bun replaces npm. Package directories resolve through
# bun, and dev tools run from the lockfile-pinned node_modules/.bin (never fetched via bunx).
PKG_DIR=$(shell bun -p "require('path').dirname(require.resolve('$(1)/package.json'))")

CATALYST_BABEL:=$(CURDIR)/node_modules/.bin/babel
CATALYST_BABEL_CONFIG:=$(call PKG_DIR,@liquid-labs/catalyst-resource-babel-and-rollup)/dist/babel/babel.config.cjs

CATALYST_ROLLUP:=$(CURDIR)/node_modules/.bin/rollup
CATALYST_ROLLUP_CONFIG:=$(call PKG_DIR,@liquid-labs/catalyst-resource-babel-and-rollup)/dist/rollup/rollup.config.mjs

CATALYST_JEST:=$(CURDIR)/node_modules/.bin/jest
CATALYST_JEST_CONFIG:=$(call PKG_DIR,@liquid-labs/catalyst-resource-jest)/dist/jest.config.js

CATALYST_ESLINT:=$(CURDIR)/node_modules/.bin/eslint
CATALYST_ESLINT_CONFIG:=$(call PKG_DIR,@liquid-labs/catalyst-resource-eslint)/dist/eslint.config.js
