# This file was generated by @liquid-labs/catalyst-builder-workflow-local-make-
# node. Refer to https://npmjs.com/package/@liquid-labs/catalyst-builder-workflow-
# local-make-node for further details

#####
# build dist/find-plus.js
#####

CATALYST_FIND_PLUS_JS:=$(DIST)/find-plus.js
CATALYST_FIND_PLUS_JS_ENTRY=$(SRC)/index.mjs
BUILD_TARGETS+=$(CATALYST_FIND_PLUS_JS)

$(CATALYST_FIND_PLUS_JS): package.json $(CATALYST_ALL_NON_TEST_JS_FILES_SRC)
	JS_BUILD_TARGET=$(CATALYST_FIND_PLUS_JS_ENTRY) \
	  JS_OUT=$@ \
	  $(CATALYST_ROLLUP) --config $(CATALYST_ROLLUP_CONFIG)

#####
# end dist/find-plus.js
#####
